# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: ":4318"
        cors:
          allowed_origins:
  zipkin:
exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]
