[package]
name = "bevy-sand"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking"] }
bevy_framepace = "0.17.1"
# bevy = "0.14.0" # stand-alone binary

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

